CS2103-AY1819S1-W17-4/main

- docs/DeveloperGuide.adoc
- src/test/java/seedu/address/ui/HelpWindowTest.java
Keep team repo up to date with changes in CS2103's main repo
> Update team repo with new commits from course repo

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/model/task/Task.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
The use is incorrect because Date(int,int,int) expects the year to be an offset from 1900.
The use is depredicated, GregorianCalendar should be used instead.
> Fixed incorrect and depreciated use of Date constructor

- build.gradle
- docs/DeveloperGuide.adoc
Change references from SE-EDU to our project group.
> Update Developer Guide

- src/main/java/seedu/address/logic/commands/SortCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/SortCommandParser.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/TaskCollection.java
- src/main/java/seedu/address/model/task/Name.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/SortCommandTest.java
- src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
What's new:
- User can sort lists using the syntax "sort name< due>", "sort d< name>"
- The user can replace the name with n and the due with d (for faster typing speed)
For v1.1 - Currently, the sorting system supports sorting with only these 2 attributes.
For v1.2 - The system should support priority and tags as well.
> Add Sort functionality [For v1.1]

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/task/Deadline.java
- src/main/java/seedu/address/model/task/Task.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/FilterCommandTest.java
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
- src/test/java/seedu/address/testutil/PersonUtil.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
- src/test/java/systemtests/AddCommandSystemTest.java
- src/test/java/systemtests/EditCommandSystemTest.java
Added comprehensive tests for all functionalities of filter, including:
- Double or single quoted values
- Any number of spaces (or no space) between key, operator, and value
- All operators: '<', '>', '=', ':', in all key contexts
> Filter: Add comprehensive tests

- src/main/java/seedu/address/model/task/Task.java
- src/main/java/seedu/address/storage/XmlAdaptedTask.java
- src/test/data/XmlSerializableTaskCollectionTest/invalidTaskInTaskCollection.xml
- src/test/data/XmlSerializableTaskCollectionTest/typicalTasksInTaskCollection.xml
- src/test/data/XmlUtilTest/validTask.xml
- src/test/data/XmlUtilTest/validTaskCollection.xml
- src/test/java/seedu/address/commons/util/XmlUtilTest.java
- src/test/java/seedu/address/storage/XmlAdaptedTaskTest.java
- src/test/java/seedu/address/ui/TaskListPanelTest.java
This will resolve #73 and resolve #3.
> Deadline import/export from XML

- src/main/java/seedu/address/logic/commands/AttachmentCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/model/attachment/Attachment.java
- src/main/java/seedu/address/model/task/Task.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/XmlAdaptedAttachment.java
- src/main/java/seedu/address/storage/XmlAdaptedTask.java
- src/test/data/XmlSerializableTaskCollectionTest/typicalTasksInTaskCollection.xml
- src/test/data/XmlUtilTest/invalidTaskField.xml
- src/test/data/XmlUtilTest/missingTaskField.xml
- src/test/data/XmlUtilTest/validTask.xml
- src/test/data/XmlUtilTest/validTaskCollection.xml
- src/test/java/seedu/address/commons/util/XmlUtilTest.java
- src/test/java/seedu/address/logic/commands/EditCommandTest.java
- src/test/java/seedu/address/model/attachment/AttachmentTest.java
- src/test/java/seedu/address/storage/XmlAdaptedTaskTest.java
- src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
- src/test/java/systemtests/AddCommandSystemTest.java
- src/test/java/systemtests/EditCommandSystemTest.java
Add checks during adding attachment to make sure file name is unique.
> Attachment: Add unique filename constraint

- src/main/java/seedu/address/logic/parser/SortCommandParser.java
- src/test/java/seedu/address/logic/commands/SortCommandTest.java
- src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Resolves #95
- Add tests for sort command
- Update tests for sort parser
> Add sort command tests + Update sort parser tests

- docs/DeveloperGuide.adoc
- docs/UserGuide.adoc
- src/main/java/seedu/address/logic/commands/SortCommand.java
- Update UserGuide with more elaborate instruction on using sort command. Also added the new sort with priority and tags.
- Updated DeveloperGuide with how the sort command is implemented. 
- Added one more example to sort command usage when it throws an error message (because of incorrect syntax)
> Update UG & DG for sort command [v1.2]

- src/main/java/seedu/address/MainApp.java
> Bump version to v1.2

- docs/UserGuide.adoc
Sorted command summary in alphabetical order.
Update glossary.
> Update UG for style

- src/main/java/seedu/address/commons/events/model/ExportRequestEvent.java
- src/main/java/seedu/address/logic/commands/ExportCommand.java
- src/main/java/seedu/address/logic/parser/ExportCommandParser.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/storage/ImportExportStorage.java
- src/main/java/seedu/address/storage/Storage.java
- src/main/java/seedu/address/storage/StorageManager.java
- src/test/java/seedu/address/logic/commands/ExportCommandTest.java
- src/test/java/seedu/address/logic/commands/ModelStub.java
- src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
- src/test/java/seedu/address/storage/StorageManagerTest.java
Add more tests to import and export commands, resolves #107 
Added new overwrite command to export command, partially fulfilling #108
>  Add overwrite flag to export parser.

- src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
- src/main/java/seedu/address/logic/parser/BooleanExpressionParser.java
- src/main/java/seedu/address/logic/parser/StringTokenizer.java
- src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
> ArgumentTokenizer: Implement quote-awareness using StringTokenizer

- src/main/java/seedu/address/logic/commands/AttachmentCommand.java
- src/main/java/seedu/address/logic/parser/AttachmentCommandParser.java
- src/main/java/seedu/address/model/attachment/Attachment.java
- src/test/java/seedu/address/logic/commands/AttachmentCommandTest.java
- src/test/java/seedu/address/logic/parser/AttachmentCommandParserTest.java
Include quoted strings
Refactor AttachmentCommand, AttachmentCommandParser to improve SLAP
> Add tests for AttachmentCommandParser

- src/main/java/seedu/address/model/task/Deadline.java
- src/test/java/seedu/address/model/task/DeadlineTest.java
> Make deadline parsing non-lenient

- src/main/java/seedu/address/logic/commands/CompleteCommand.java
- src/main/java/seedu/address/logic/parser/CompleteCommandParser.java
- src/main/java/seedu/address/logic/parser/TaskCollectionParser.java
- src/main/java/seedu/address/model/task/Deadline.java
- src/main/java/seedu/address/model/task/Frequency.java
#132 
Add `CompleteCommand`
Syntax:
`complete INDEX`
Behaviour:
If the task is a recurring task, this command will change the deadline to the next occurrence.
Otherwise, the task will be deleted.
PS: Please merge first, I will write tests and update doc later.
> Add CompleteCommand

- docs/UserGuide.adoc
- src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
> Update UG + Tests for sort cmd

- src/main/java/seedu/address/logic/parser/FilterCommandParser.java
- src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
> Implement character restrictions on unquoted filters

- docs/DeveloperGuide.adoc
#132 
Update DG for add command and complete command
> Update DG for add command and complete command

- src/main/java/seedu/address/model/attachment/Attachment.java
- src/test/java/seedu/address/logic/commands/AttachmentCommandTest.java
> Fix AttachmentCommand bug when user provides invalid characters in path

- src/main/java/seedu/address/MainApp.java
> Update version number.

- docs/DeveloperGuide.adoc
- docs/UserGuide.adoc
- docs/team/ranaldmiao.adoc
Minor updates to User Guide
Some rephrasing of wordings for Developer Guide for AttachmentCommand
> Add Ranald's PPP

- docs/UserGuide.adoc
- docs/team/ranaldmiao.adoc
Fixes #236 
Both in attachments section,
and Import section.
@sijie123 I have edited User Guide section 3.12, please review :)
> Add mention about filenames with quotation marks in User Guide

- src/main/java/seedu/address/model/ModelManager.java
> ImportExport: Support undo for import

- src/main/java/seedu/address/logic/commands/FilterCommand.java
- src/main/java/seedu/address/logic/parser/FilterCommandParser.java
- src/main/java/seedu/address/model/util/SetUtil.java
- src/test/java/seedu/address/logic/parser/tokenizer/StringTokenizerTest.java
This inline help is displayed to the user when `filter` is typed without any filter expression.  This resolves #255.
> Filter: Add better inline help

- docs/UserGuide.adoc
> Fix incorrect .jar file name in user guide

- docs/UserGuide.adoc
> UserGuide: Mention that DeadlineManager is not timezone-aware

- docs/team/ranaldmiao.adoc
Trying to cut content and the number of pages
> Update Ranald's PPP

- src/main/java/seedu/address/logic/parser/SortCommandParser.java
> Fix incomplete tag command for sort

- docs/UserGuide.adoc
- docs/team/ranaldmiao.adoc
To be in sync with Import/Export regarding the tip for FILENAME and FILEPATH.
> Update Ranald's PPP and User Guide for Attachments

- src/main/java/seedu/address/logic/commands/AttachmentCommand.java
> Refactor AttachmentCommand

- src/main/java/seedu/address/logic/parser/SortCommandParser.java
- src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
> Remove magic constants from sort

- src/test/java/seedu/address/storage/StorageManagerTest.java
The checks are platform specific, but I wrote one for each platform.
On Windows platforms, the Unix tests are skipped, and vice versa.
> [WIP] Add checks to import export storage

- src/main/java/seedu/address/model/task/Frequency.java
> Fix frequency error message to say "integer" not "number"

- docs/DeveloperGuide.adoc
- docs/UserGuide.adoc
- docs/team/ranaldmiao.adoc
> Update Ranald PPP

- docs/DeveloperGuide.adoc
- docs/team/kc97ble.adoc
Update Instructions for Manual Testing for COMPLETE command
> Update Instructions for Manual Testing for COMPLETE command

- docs/DeveloperGuide.adoc
> Standardize developer guide capitalisation

- src/main/java/seedu/address/MainApp.java
> Bump version number
